platform :ios, '9.0'

use_frameworks!

target 'Examples' do

    # Pods for Examples
    pod 'AffirmSDK', :path => '../'

end

target 'ExamplesSwift' do

    # Pods for ExamplesSwift
    pod 'AffirmSDK', :path => '../'

end
